local lwl = mods.lightweight_lua
local lwui = mods.lightweight_user_interface
local Brightness = mods.brightness

--[[
Brightness animatables: Brighness should be a library that lets you make things with arbitrary render functions.
That's wrong, Brightness is about particles, but the logic of tracking things and rotating and positioning and rendering them should be centralized.
Because then I can use that rendering library for both my stuff and brightness, and I get rotations out of it.

Because I want to use objects instead of particles because objects can render as rectangles that I can set the size of in code.
It's tricky, because I have a library that I want LWL and Brightness to consume, but LWL uses Brightness right now.
I could ask Brightlord if I can eat his mod to avoid having another mod.
I also want to pull out the object caching thing for images and have that be a library and the default everyone uses.
I'm dumb, I can just make them libraries inside of Brightness and I don't have to change anything.
So that's extracting the image repo, and the rendering registration.
The image repo will be easier.

For now I'll just use brightness.
Use Brightness and get this working, then do the deep internal work while I'm in it.
17.5//

--Particle must be present when cells are enabled.
]]

mods.lims_ships = {}
mods.lims_ships.Cell = {}
local Cell = mods.lims_ships.Cell
Cell.__index = Cell

local RENDER_LAYER = "SHIP_MANAGER"
--Takes two points, but the one is absolute and one is relative to the absolute one.
local function addOffset(point, offset)
    return Hyperspace.Pointf(point.x + offset.x, point.y + offset.y)
end

-- getters
function Cell:isAlive() return self._alive end
function Cell:isEnabled() return self._enabled end
function Cell:getNextAlive() return self._nextAlive end
-- geometry
function Cell:getBoardPosition() return self._boardPosition end
function Cell:getOffset() return self._offset end
function Cell:getSize() return self._width, self._height end

---comment
---@param position Hyperspace.Pointf
function Cell:updatePosition(position)
    if not self:isEnabled() then return end
    self._particle.position = addOffset(position, self:getOffset())
    --print("updating position for particle, is now", self._particle.position.x, self._particle.position.y)
end


---Turns a cell alive or dead.
---@param state boolean
function Cell:setAlive(state)
    --print("cell being alive?", state, self._boardPosition.x, self._boardPosition.y, self:isEnabled())
    if self:isEnabled() then
        --print("turning particle on")
        self._particle.visible = state
    end
    self._alive = state
end

--boolean
function Cell:setNextAlive(value)
    self._nextAlive = value
end

---Updates to next state
function Cell:commit()
    self:setAlive(self._nextAlive)
end

function Cell:setRenderSpace(space)
    -- self._renderSpace = space
    -- if self:isEnabled() then
    --     self._particle.space = space
    -- end
end

-- enabled
function Cell:setEnabled(enabled)
    self._enabled = enabled
    if not enabled then
        self:setAlive(false)
        self:setNextAlive(false)
        if (self._particle ~= nil) then
            Brightness.destroy_particle(self._particle)
            self._particle = nil
        end
    else
        self._particle = Brightness.create_particle("particles/game_of_life/1", 1, 1, Hyperspace.Pointf(0,0), 0, 0, RENDER_LAYER)
        self._particle.persists = true
    end
end

--- Autogenerated by GPT 4?
--- square grid, square cells.
---@param x number Non-negative
---@param y number Non-negative
---@param size number 
---@return table
function Cell.new(x, y, size, renderSpace)
    local self = setmetatable({}, Cell)
    local xOffset = (x - 1) * size
    local yOffset = (y - 1) * size

    self._boardPosition = {x=x, y=y}
    self._offset = {x=xOffset, y=yOffset}
    self._width = size
    self._height = size
    self._renderSpace = renderSpace

    self:setEnabled(true)
    self._alive     = false
    self._nextAlive = false

    return self
end